unit hope;

interface

	const
		HTLC_HDR_FILE_HASH = $EE0;
		HTLC_DATA_HASH_MD5 = $E80;
		HTLC_DATA_HASH_HAVAL = $E81;
		HTLC_DATA_HASH_SHA1 = $E82;
		HTLC_DATA_ICON_CICN = $E90;
		HTLS_DATA_SID = $E67;
		DATA_SESSIONKEY = $E03;
		DATA_MAC_ALG = $E04;
		HTLS_DATA_CIPHER_ALG = $EC1;
		HTLC_DATA_CIPHER_ALG = $EC2;
		HTLS_DATA_CIPHER_MODE = $EC3;
		HTLC_DATA_CIPHER_MODE = $EC4;
		HTLS_DATA_CIPHER_IVEC = $EC5;
		HTLC_DATA_CIPHER_IVEC = $EC6;
		HTLS_DATA_CHECKSUM_ALG = $EC7;
		HTLC_DATA_CHECKSUM_ALG = $EC8;
		HTLS_DATA_COMPRESS_ALG = $EC9;
		HTLC_DATA_COMPRESS_ALG = $ECA;

implementation

end.
